"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1000
scan_timeout = 30

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$golang\
$nodejs\
$python\
$rust\
$java\
$docker_context\
$status\
$cmd_duration\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[username]
show_always = true
style_user = "bold fg:black bg:bright-white"
style_root = "bold fg:red bg:bright-white"
format = "[ $user ]($style)[](fg:bright-white bg:bright-black)"

[directory]
style = "bold fg:black bg:bright-black"
read_only = " "
read_only_style = "bold fg:red bg:bright-black"
format = "[ $path ]($style)[$read_only]($read_only_style)[](fg:bright-black) "
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "

[git_branch]
symbol = ""
style = "bold fg:black bg:yellow"
format = "[](fg:black bg:bright-white)[ $symbol ](bold fg:yellow bg:bright-white)[](fg:bright-white bg:yellow)[ $branch ]($style)[](fg:yellow)"

[git_status]
style = "bold fg:yellow"
format = "[ $all_status$ahead_behind]($style) "
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[c]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[golang]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "bright-black"
format = "[$symbol$version]($style) "

[docker_context]
symbol = " "
style = "bright-black"
format = "[$symbol$context]($style) "

[status]
disabled = false
symbol = "✘ "
style = "bold red"
format = "[$symbol$status]($style) "

[cmd_duration]
min_time = 1500
style = "bright-black"
format = "[$duration]($style) "

[time]
disabled = false
time_format = "%T"
style = "bold fg:black bg:bright-black"
format = "[](fg:bright-black)[  $time ]($style)"

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold yellow) "
error_symbol = "[❯](bold red) "
vimcmd_symbol = "[❮](bold yellow) "
